### ISSUE TITLE
preg_replace(): Compilation failed

### ISSUE THREAD

**Issue by d0ublezer0** [dryabov/rustypo#2]
16 версия
Warning: preg_replace(): Compilation failed: range out of order in character class at offset 25 in W:\home\apriori\www\plugins\content\rustypo\rustypo.php on line 72

Я в regex синтаксисе не оч понимаю, точнее вообще никак. Но что-то нарыл.
было
Код:

// ПРЯМАЯ РЕЧЬ
    if( $params->get( 'speech' ) ) $text = preg_replace( '/(^|<p>|<br>|<br \/>)[\s*- /u','\\1— ', $text ); // Прямая речь - дефис в начале строки и после тегов <p>, <br> и <br />

поправил на
Код:

// ПРЯМАЯ РЕЧЬ
    if( $params->get( 'speech' ) ) $text = preg_replace( '/(^|<p>|<br>|<br \/>)[\s*-] /u','\\1— ', $text ); // Прямая речь - дефис в начале строки и после тегов <p>, <br> и <br />

и ошибка исчезла

**Comment by dryabov** [comment]
Исправлено (квадратная скобка была лишней).
